import { RAW_DECKS } from '@entity-builders/deck-engine';
import type { Card, RawDeckContent } from '@entity-builders/deck-engine';

function sqlString(value: unknown): string {
  if (value === null || value === undefined) {
    return 'NULL';
  }

  return `'${String(value).replaceAll("'", "''")}'`;
}

function sqlJson(value: unknown): string {
  return sqlString(JSON.stringify(value ?? null));
}

function editionRow(deck: RawDeckContent): string {
  return [
    sqlString(deck.slug),
    sqlString(deck.name),
    sqlString(deck.description),
    sqlString(deck.language),
    String(deck.cards.length),
    sqlString(deck.print_spec_id),
    sqlString(deck.design_template_id),
    sqlJson(deck.print_specs_overrides ?? {}),
    sqlJson(deck.design_template_overrides ?? {}),
    sqlJson(deck.landing_config ?? {}),
    sqlJson(deck.metadata ?? {}),
    sqlJson(deck.pricing ?? {}),
    sqlJson(deck.digital ?? {}),
    sqlString('deck-engine'),
    "datetime('now')",
  ].join(', ');
}

function cardRow(deck: RawDeckContent, card: Card): string {
  return [
    sqlString(card.id),
    sqlString(deck.slug),
    String(card.front.number),
    sqlJson(card.front),
    sqlJson(card.back),
    sqlJson(card.tags ?? []),
    sqlString('deck-engine'),
    "datetime('now')",
  ].join(', ');
}

const decks = Object.values(RAW_DECKS);
const deckSlugs = decks.map((deck) => sqlString(deck.slug)).join(', ');

console.log('-- Auto-generated by apps/baraja/scripts/generate_d1_deck_seed.ts');
console.log(`DELETE FROM baraja_cards WHERE edition_slug IN (${deckSlugs});`);

for (const deck of decks) {
  console.log(`
INSERT INTO baraja_editions (
  slug,
  name,
  description,
  language,
  card_count,
  print_spec_id,
  design_template_id,
  print_specs_overrides,
  design_template_overrides,
  landing_config,
  metadata,
  pricing,
  digital,
  source,
  updated_at
) VALUES (${editionRow(deck)})
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  description = excluded.description,
  language = excluded.language,
  card_count = excluded.card_count,
  print_spec_id = excluded.print_spec_id,
  design_template_id = excluded.design_template_id,
  print_specs_overrides = excluded.print_specs_overrides,
  design_template_overrides = excluded.design_template_overrides,
  landing_config = excluded.landing_config,
  metadata = excluded.metadata,
  pricing = excluded.pricing,
  digital = excluded.digital,
  source = excluded.source,
  updated_at = excluded.updated_at;`);

  for (const card of deck.cards) {
    console.log(`
INSERT INTO baraja_cards (
  id,
  edition_slug,
  number,
  front,
  back,
  tags,
  source,
  updated_at
) VALUES (${cardRow(deck, card)})
ON CONFLICT(id) DO UPDATE SET
  edition_slug = excluded.edition_slug,
  number = excluded.number,
  front = excluded.front,
  back = excluded.back,
  tags = excluded.tags,
  source = excluded.source,
  updated_at = excluded.updated_at;`);
  }
}
