export interface BarajaMusicBingoSeedCollection {
  id: string;
  name: string;
  description: string;
  catalog: BarajaMusicBingoSeedCatalogMetadata;
  market: string;
  isPublic: boolean;
  minimumSongCount: number;
  seededSongCount?: number;
  spotifyUrl?: string;
  targetSongCount: number;
  songs: string[];
}

export interface BarajaMusicBingoSeedCatalogMetadata {
  categoryId: string;
  categoryLabel: string;
  genreLabel: string;
  occasionLabels: string[];
  energyLabel: string;
  decadeLabel?: string;
  supportedBoardSizes: Array<3 | 4 | 5>;
  useCaseLabel: string;
  searchTerms: string[];
}

export const BARAJA_MUSIC_BINGO_SEED_COLLECTIONS: BarajaMusicBingoSeedCollection[] = [
  {
    id: 'rock-argentino-esenciales',
    name: 'Baraja Bingo - Rock Argentino Esenciales',
    description: 'Rock argentino reconocible para bingo musical Baraja. Seed inicial, revisar matches antes de publicar.',
    catalog: {
      categoryId: 'rock',
      categoryLabel: 'Rock',
      genreLabel: 'Rock argentino',
      occasionLabels: ['Para cantar', 'Clasicos'],
      energyLabel: 'Nostalgia alta',
      decadeLabel: '80/90/00',
      supportedBoardSizes: [3, 4, 5],
      useCaseLabel: 'Cumpleanos, previa o mesa adulta',
      searchTerms: ['rock nacional', 'rock argentino', 'soda', 'charly', 'calamaro'],
    },
    market: 'AR',
    isPublic: false,
    minimumSongCount: 96,
    seededSongCount: 48,
    spotifyUrl: 'https://open.spotify.com/playlist/5RwRJ1m1SgF7hPnn4ZBaMr',
    targetSongCount: 120,
    songs: [
      'Soda Stereo - De musica ligera',
      'Soda Stereo - Persiana americana',
      'Soda Stereo - Cuando pase el temblor',
      'Soda Stereo - En la ciudad de la furia',
      'Soda Stereo - Profugos',
      'Gustavo Cerati - Crimen',
      'Gustavo Cerati - Adios',
      'Charly Garcia - Nos siguen pegando abajo',
      'Charly Garcia - Demoliendo hoteles',
      'Charly Garcia - No voy en tren',
      'Charly Garcia - Los dinosaurios',
      'Seru Giran - Seminare',
      'Seru Giran - Viernes 3 AM',
      'Fito Paez - Mariposa tecknicolor',
      'Fito Paez - 11 y 6',
      'Fito Paez - El amor despues del amor',
      'Fito Paez - Dar es dar',
      'Los Abuelos de la Nada - Mil horas',
      'Los Abuelos de la Nada - Costumbres argentinas',
      'Miguel Mateos - Cuando seas grande',
      'Miguel Mateos - Atado a un sentimiento',
      'Virus - Pronta entrega',
      'Virus - Una luna de miel en la mano',
      'Virus - Wadu Wadu',
      'Los Enanitos Verdes - Lamento boliviano',
      'Los Enanitos Verdes - La muralla verde',
      'Los Enanitos Verdes - Tus viejas cartas',
      'Los Fabulosos Cadillacs - Matador',
      'Los Fabulosos Cadillacs - Vasos vacios',
      'Los Fabulosos Cadillacs - Siguiendo la luna',
      'Patricio Rey y sus Redonditos de Ricota - Jijiji',
      'Patricio Rey y sus Redonditos de Ricota - Un angel para tu soledad',
      'Patricio Rey y sus Redonditos de Ricota - La bestia pop',
      'Andres Calamaro - Flaca',
      'Andres Calamaro - Loco',
      'Andres Calamaro - Mil horas',
      'Los Rodriguez - Sin documentos',
      'Los Rodriguez - Para no olvidar',
      'Babasonicos - Irresponsables',
      'Babasonicos - Putita',
      'Babasonicos - Carismatico',
      'Ciro y los Persas - Antes y despues',
      'Ciro y los Persas - Me gusta',
      'La Renga - El final es en donde parti',
      'La Renga - La razon que te demora',
      'Divididos - Spaghetti del rock',
      'Divididos - Que ves',
      'Las Pelotas - Sera',
      'Soda Stereo - Sobredosis de TV',
      'Soda Stereo - Signos',
      'Soda Stereo - Tratame suavemente',
      'Soda Stereo - Nada personal',
      'Soda Stereo - Zoom',
      'Soda Stereo - Primavera 0',
      'Soda Stereo - Te hacen falta vitaminas',
      'Gustavo Cerati - Puente',
      'Gustavo Cerati - Bocanada',
      'Gustavo Cerati - Lago en el cielo',
      'Gustavo Cerati - Cosas imposibles',
      'Gustavo Cerati - Rapto',
      'Gustavo Cerati - La excepcion',
      'Charly Garcia - Rezo por vos',
      'Charly Garcia - Promesas sobre el bidet',
      'Charly Garcia - Cerca de la revolucion',
      'Charly Garcia - Chipi chipi',
      'Charly Garcia - Yendo de la cama al living',
      'Charly Garcia - Filosofia barata y zapatos de goma',
      'Seru Giran - Peperina',
      'Seru Giran - Eiti Leda',
      'Seru Giran - Cancion de Alicia en el pais',
      'Sui Generis - Rasguna las piedras',
      'Sui Generis - Confesiones de invierno',
      'Sui Generis - Necesito',
      'Fito Paez - Circo beat',
      'Fito Paez - Tumbas de la gloria',
      'Fito Paez - Al lado del camino',
      'Fito Paez - Brillante sobre el mic',
      'Fito Paez - A rodar mi vida',
      'Los Abuelos de la Nada - Himno de mi corazon',
      'Los Abuelos de la Nada - Lunes por la madrugada',
      'Miguel Mateos - Tira para arriba',
      'Miguel Mateos - Perdiendo el control',
      'Miguel Mateos - Obsesion',
      'Virus - Amor descartable',
      'Virus - Imagenes paganas',
      'Virus - Mirada speed',
      'Los Enanitos Verdes - Te vi en un tren',
      'Los Enanitos Verdes - Guitarras blancas',
      'Los Enanitos Verdes - Por el resto',
      'Los Fabulosos Cadillacs - Mal bicho',
      'Los Fabulosos Cadillacs - El satanico Dr Cadillac',
      'Los Fabulosos Cadillacs - Manuel Santillan el leon',
      'Los Fabulosos Cadillacs - Calaveras y diablitos',
      'Patricio Rey y sus Redonditos de Ricota - Mi perro dinamita',
      'Patricio Rey y sus Redonditos de Ricota - Todo un palo',
      'Patricio Rey y sus Redonditos de Ricota - Masacre en el puticlub',
      'Patricio Rey y sus Redonditos de Ricota - Queso ruso',
      'Andres Calamaro - Te quiero igual',
      'Andres Calamaro - Paloma',
      'Andres Calamaro - Alta suciedad',
      'Andres Calamaro - Estadio azteca',
      'Andres Calamaro - Los aviones',
      'Los Rodriguez - Mucho mejor',
      'Los Rodriguez - Mi enfermedad',
      'Los Rodriguez - Dulce condena',
      'Babasonicos - Yegua',
      'Babasonicos - El colmo',
      'Babasonicos - Los calientes',
      'Babasonicos - Microdancing',
      'Los Piojos - Verano del 92',
      'Los Piojos - El farolito',
      'Los Piojos - Tan solo',
      'Los Piojos - Como Ali',
      'La Renga - Balada del diablo y la muerte',
      'La Renga - Panic show',
      'Divididos - Amapola del 66',
      'Divididos - Par mil',
      'Las Pelotas - El ojo blindado',
      'Attaque 77 - Arrancacorazones',
      'Bersuit Vergarabat - Un pacto',
    ],
  },
  {
    id: 'cumbia-cuarteto-argentina',
    name: 'Baraja Bingo - Cumbia y Cuarteto Argentina',
    description: 'Cumbia, cuarteto y fiesta popular argentina para eventos familiares y bares.',
    catalog: {
      categoryId: 'cumbia',
      categoryLabel: 'Cumbia',
      genreLabel: 'Cumbia y cuarteto',
      occasionLabels: ['Fiesta', 'Baile'],
      energyLabel: 'Bailable',
      decadeLabel: 'Popular',
      supportedBoardSizes: [3, 4, 5],
      useCaseLabel: 'Cumpleanos, bares y reuniones familiares',
      searchTerms: ['cumbia', 'cuarteto', 'fiesta', 'baile', 'argentina'],
    },
    market: 'AR',
    isPublic: false,
    minimumSongCount: 96,
    seededSongCount: 48,
    spotifyUrl: 'https://open.spotify.com/playlist/0GwnwIg5ahqiJdOT7cChYf',
    targetSongCount: 120,
    songs: [
      'Los Palmeras - Bombon asesino',
      'Los Palmeras - El embrujo',
      'Los Palmeras - Soy sabalero',
      'Los Palmeras - Doble vida',
      'Rafaga - Mentirosa',
      'Rafaga - Una cerveza',
      'Rafaga - Aguita',
      'Amar Azul - Yo me enamore',
      'Amar Azul - El polvito del amor',
      'Amar Azul - Yo tomo licor',
      'Damas Gratis - No te creas tan importante',
      'Damas Gratis - Se te ve la tanga',
      'Damas Gratis - Laura',
      'Pibes Chorros - Que calor',
      'Pibes Chorros - Duraznito',
      'Yerba Brava - La cumbia de los trapos',
      'Yerba Brava - Pibe cantina',
      'Antonio Rios - Nunca me faltes',
      'Antonio Rios - Amor de lejos',
      'Gilda - No me arrepiento de este amor',
      'Gilda - Fuiste',
      'Gilda - Paisaje',
      'Rodrigo - Soy cordobes',
      'Rodrigo - La mano de Dios',
      'Rodrigo - Lo mejor del amor',
      'La Konga - Universo paralelo',
      'La Konga - Ya no vuelvas',
      'La Konga - El mismo aire',
      'Q Lokura - Ya no te buscare',
      'Q Lokura - 200 copas',
      'Banda XXI - Que bonito',
      'Banda XXI - Olvidala',
      'Ulises Bueno - Intento',
      'Ulises Bueno - Dale vieja dale',
      'La Mona Jimenez - Beso a beso',
      'La Mona Jimenez - Quien se ha tomado todo el vino',
      'Karina - Con la misma moneda',
      'Karina - Corazon mentiroso',
      'Angela Leiva - Amiga traidora',
      'Nestor en Bloque - Una calle nos separa',
      'El Polaco - Deja de llorar',
      'El Polaco - Te conoci',
      'La Nueva Luna - Iluminara',
      'La Nueva Luna - Y ahora te vas',
      'Grupo Sombras - La ventanita',
      'Leo Mattioli - Le pido a Dios',
      'Rombai - Cuando se pone a bailar',
      'Marama - Nena',
      'Los Palmeras - La suavecita',
      'Los Palmeras - Olvidala',
      'Los Palmeras - Muchacha triste',
      'Los Palmeras - El bombon',
      'Rafaga - Maldito corazon',
      'Rafaga - La luna y tu',
      'Rafaga - Una rafaga de amor',
      'Amar Azul - Yo soy el campeon',
      'Amar Azul - Te necesito',
      'Amar Azul - Gracias a Dios',
      'Damas Gratis - Los duenos del pabellon',
      'Damas Gratis - Me vas a extranar',
      'Damas Gratis - No te pongas gorra',
      'Damas Gratis - Soy de la esquina',
      'Pibes Chorros - El tano pastita',
      'Pibes Chorros - La colorada',
      'Pibes Chorros - Llegamos los pibes chorros',
      'Yerba Brava - La lata',
      'Yerba Brava - El viejo de arriba',
      'Antonio Rios - Amigo mio',
      'Antonio Rios - No me acostumbro',
      'Antonio Rios - Si tu supieras',
      'Gilda - Se me ha perdido un corazon',
      'Gilda - Corazon valiente',
      'Gilda - Noches vacias',
      'Rodrigo - Ocho cuarenta',
      'Rodrigo - Fuego y pasion',
      'Rodrigo - Amor clasificado',
      'Rodrigo - Yerba mala',
      'La Konga - Te mentiria',
      'La Konga - Ya no mas',
      'La Konga - Adicto',
      'La Konga - Fama de diabla',
      'Q Lokura - Que me falte todo',
      'Q Lokura - Disfruto',
      'Q Lokura - La cabra',
      'Banda XXI - Se termino',
      'Banda XXI - Y que',
      'Banda XXI - La chica del baile',
      'Ulises Bueno - Ahora mirame',
      'Ulises Bueno - Intento olvidarte',
      'Ulises Bueno - Soy',
      'La Mona Jimenez - El marginal',
      'La Mona Jimenez - Ramito de violetas',
      'La Mona Jimenez - La flaca Marta',
      'Karina - Te quise olvidar',
      'Karina - Sin verguenza',
      'Karina - Fuera',
      'Angela Leiva - Solita',
      'Angela Leiva - Me duele',
      'Angela Leiva - Dejame',
      'Nestor en Bloque - Te amo',
      'Nestor en Bloque - Sos mi vida',
      'El Polaco - Solo',
      'El Polaco - Vuelve te lo pido',
      'La Nueva Luna - Te vas a arrepentir',
      'La Nueva Luna - Jurabas tu',
      'Grupo Sombras - Boquita de caramelo',
      'Grupo Sombras - Una copa mas',
      'Leo Mattioli - Como podre',
      'Leo Mattioli - Con el no eres feliz',
      'Leo Mattioli - Despreciame',
      'Rombai - 2 pa 2',
      'Rombai - Me voy',
      'Rombai - Yo tambien',
      'Marama - Todo comenzo bailando',
      'Marama - Loquita',
      'Marama - Bronceado',
      'Ke Personajes - Un finde',
      'Ke Personajes - Pobre corazon',
      'Luck Ra - La morocha',
      'La Delio Valdez - Inocente',
    ],
  },
  {
    id: 'reggaeton-latino-clasico',
    name: 'Baraja Bingo - Reggaeton Latino Clasico',
    description: 'Reggaeton y urbano latino reconocible para fiestas de adultos.',
    catalog: {
      categoryId: 'urbano',
      categoryLabel: 'Urbano',
      genreLabel: 'Reggaeton latino',
      occasionLabels: ['Fiesta adulta', 'Baile'],
      energyLabel: 'Alta energia',
      decadeLabel: '2000/2010/2020',
      supportedBoardSizes: [3, 4, 5],
      useCaseLabel: 'Fiestas con publico joven o adulto',
      searchTerms: ['reggaeton', 'urbano', 'latino', 'fiesta', 'perreo'],
    },
    market: 'AR',
    isPublic: false,
    minimumSongCount: 96,
    seededSongCount: 48,
    spotifyUrl: 'https://open.spotify.com/playlist/5ibeFUV9MUA9dapqbrGetn',
    targetSongCount: 120,
    songs: [
      'Daddy Yankee - Gasolina',
      'Daddy Yankee - Lo que paso paso',
      'Daddy Yankee - Rompe',
      'Daddy Yankee - Limbo',
      'Daddy Yankee - Dura',
      'Don Omar - Danza Kuduro',
      'Don Omar - Dile',
      'Don Omar - Pobre diabla',
      'Don Omar - Salio el sol',
      'Wisin y Yandel - Rakata',
      'Wisin y Yandel - Abusadora',
      'Wisin y Yandel - Algo me gusta de ti',
      'Tego Calderon - Pa que retozen',
      'Tego Calderon - Guasa guasa',
      'Ivy Queen - Yo quiero bailar',
      'Ivy Queen - Quiero saber',
      'Plan B - Candy',
      'Plan B - Fanatica sensual',
      'Zion y Lennox - Otra vez',
      'Zion y Lennox - Yo voy',
      'Nicky Jam - Travesuras',
      'Nicky Jam - El perdon',
      'J Balvin - Ginza',
      'J Balvin - Mi gente',
      'J Balvin - Safari',
      'Maluma - Borro cassette',
      'Maluma - Felices los 4',
      'Ozuna - Se preparo',
      'Ozuna - Dile que tu me quieres',
      'Bad Bunny - Callaita',
      'Bad Bunny - Si veo a tu mama',
      'Bad Bunny - Titi me pregunto',
      'Karol G - Tusa',
      'Karol G - Bichota',
      'Natti Natasha - Criminal',
      'Becky G - Mayores',
      'Becky G - Sin pijama',
      'Rauw Alejandro - Todo de ti',
      'Feid - Feliz cumpleanos Ferxxo',
      'Calle 13 - Atrevete te te',
      'Calle 13 - No hay nadie como tu',
      'Chino y Nacho - Nina bonita',
      'Enrique Iglesias - Bailando',
      'CNCO - Reggaeton lento',
      'Sebastian Yatra - Traicionera',
      'Piso 21 - Me llamas',
      'Manuel Turizo - Una lady como tu',
      'Myke Towers - La curiosidad',
      'Daddy Yankee - Shaky Shaky',
      'Daddy Yankee - Con calma',
      'Daddy Yankee - Ella me levanto',
      'Daddy Yankee - La despedida',
      'Don Omar - Taboo',
      'Don Omar - Virtual diva',
      'Don Omar - Dale don dale',
      'Don Omar - Hasta abajo',
      'Wisin y Yandel - Sexy movimiento',
      'Wisin y Yandel - Pam pam',
      'Wisin y Yandel - Estoy enamorado',
      'Wisin y Yandel - Noche de sexo',
      'Tego Calderon - Metele sazon',
      'Tego Calderon - Los mate',
      'Ivy Queen - Dime',
      'Ivy Queen - La vida es asi',
      'Ivy Queen - Que lloren',
      'Plan B - Es un secreto',
      'Plan B - Si no le contesto',
      'Plan B - Mi vecinita',
      'Zion y Lennox - La player',
      'Zion y Lennox - Pierdo la cabeza',
      'Zion y Lennox - Mi tesoro',
      'Nicky Jam - Hasta el amanecer',
      'Nicky Jam - El amante',
      'Nicky Jam - X',
      'Nicky Jam - Te robare',
      'J Balvin - 6 AM',
      'J Balvin - Ay vamos',
      'J Balvin - Sigo extranandote',
      'J Balvin - Bobo',
      'Maluma - Sin contrato',
      'Maluma - El perdedor',
      'Maluma - Hawai',
      'Maluma - Sobrio',
      'Ozuna - La modelo',
      'Ozuna - Caramelo',
      'Ozuna - Baila baila baila',
      'Bad Bunny - Dakiti',
      'Bad Bunny - Yonaguni',
      'Bad Bunny - Me porto bonito',
      'Bad Bunny - Moscow mule',
      'Bad Bunny - Neverita',
      'Bad Bunny - Ojitos lindos',
      'Karol G - Provenza',
      'Karol G - Ay Dios mio',
      'Karol G - Amargura',
      'Karol G - Mi ex tenia razon',
      'Natti Natasha - La mejor version de mi',
      'Natti Natasha - No me acuerdo',
      'Becky G - Mala santa',
      'Becky G - Baile con mi ex',
      'Rauw Alejandro - Desesperados',
      'Rauw Alejandro - 2/catorce',
      'Rauw Alejandro - Tattoo remix',
      'Feid - Normal',
      'Feid - Chorrito pa las animas',
      'Feid - Ferxxo 100',
      'Feid - Classy 101',
      'Calle 13 - Muerte en Hawaii',
      'Calle 13 - La vuelta al mundo',
      'Chino y Nacho - Me voy enamorando',
      'Chino y Nacho - Tu angelito',
      'CNCO - Hey DJ',
      'Sebastian Yatra - Robarte un beso',
      'Piso 21 - Dejame',
      'Manuel Turizo - La bachata',
      'Manuel Turizo - Culpables',
      'Myke Towers - Diosa',
      'Myke Towers - Pareja del ano',
      'Arcangel - Me prefieres a mi',
      'Jowell y Randy - No te veo',
    ],
  },
  {
    id: 'pop-latino-2000s',
    name: 'Baraja Bingo - Pop Latino 2000s',
    description: 'Pop latino y hits en espanol de 1995 a 2015 para juegos multigeneracionales.',
    catalog: {
      categoryId: 'pop',
      categoryLabel: 'Pop',
      genreLabel: 'Pop latino',
      occasionLabels: ['Multigeneracional', 'Nostalgia'],
      energyLabel: 'Cantable',
      decadeLabel: '1995/2015',
      supportedBoardSizes: [3, 4, 5],
      useCaseLabel: 'Familia, amigos y eventos mixtos',
      searchTerms: ['pop latino', 'shakira', 'ricky martin', 'mana', 'latino'],
    },
    market: 'AR',
    isPublic: false,
    minimumSongCount: 96,
    seededSongCount: 48,
    spotifyUrl: 'https://open.spotify.com/playlist/3QOqhnX59kNLHfsj3gqBB1',
    targetSongCount: 120,
    songs: [
      'Shakira - Antologia',
      'Shakira - Estoy aqui',
      'Shakira - Suerte',
      'Shakira - La tortura',
      'Shakira - Hips dont lie',
      'Ricky Martin - Livin la vida loca',
      'Ricky Martin - Maria',
      'Ricky Martin - La mordidita',
      'Enrique Iglesias - Heroe',
      'Enrique Iglesias - Bailamos',
      'Enrique Iglesias - Duele el corazon',
      'Luis Fonsi - Despacito',
      'Luis Fonsi - No me doy por vencido',
      'Chayanne - Torero',
      'Chayanne - Dejaria todo',
      'Chayanne - Salome',
      'Marc Anthony - Vivir mi vida',
      'Marc Anthony - Valio la pena',
      'Mana - Rayando el sol',
      'Mana - Labios compartidos',
      'Mana - En el muelle de San Blas',
      'Juanes - A Dios le pido',
      'Juanes - La camisa negra',
      'Juanes - Me enamora',
      'Alejandro Sanz - Corazon partio',
      'Alejandro Sanz - Amiga mia',
      'La Oreja de Van Gogh - Rosas',
      'La Oreja de Van Gogh - La playa',
      'La Oreja de Van Gogh - Puedes contar conmigo',
      'Julieta Venegas - Me voy',
      'Julieta Venegas - Limon y sal',
      'Julieta Venegas - Eres para mi',
      'Paulina Rubio - Y yo sigo aqui',
      'Paulina Rubio - Ni una sola palabra',
      'Thalia - A quien le importa',
      'Thalia - Amor a la mexicana',
      'Belanova - Rosa pastel',
      'Belanova - Baila mi corazon',
      'Miranda - Don',
      'Miranda - Perfecta',
      'Miranda - Yo te dire',
      'Sin Bandera - Entra en mi vida',
      'Reik - Yo quisiera',
      'Camila - Todo cambio',
      'Alex Ubago - Sin miedo a nada',
      'Natalia Lafourcade - En el 2000',
      'Bacilos - Caraluna',
      'Bacilos - Mi primer millon',
      'Shakira - Inevitable',
      'Shakira - Ciega sordomuda',
      'Shakira - Ojos asi',
      'Shakira - No creo',
      'Shakira - Que me quedes tu',
      'Shakira - Las de la intuicion',
      'Ricky Martin - She Bangs',
      'Ricky Martin - Vuelve',
      'Ricky Martin - Tal vez',
      'Ricky Martin - Tu recuerdo',
      'Enrique Iglesias - Experiencia religiosa',
      'Enrique Iglesias - Escape',
      'Enrique Iglesias - Subeme la radio',
      'Enrique Iglesias - Nunca te olvidare',
      'Luis Fonsi - Aqui estoy yo',
      'Luis Fonsi - Quien te dijo eso',
      'Luis Fonsi - Echame la culpa',
      'Chayanne - Provocame',
      'Chayanne - Y tu te vas',
      'Chayanne - Un siglo sin ti',
      'Chayanne - Madre tierra',
      'Marc Anthony - Tu amor me hace bien',
      'Marc Anthony - Ahora quien',
      'Marc Anthony - Flor palida',
      'Marc Anthony - Y hubo alguien',
      'Mana - Clavado en un bar',
      'Mana - Mariposa traicionera',
      'Mana - Bendita tu luz',
      'Mana - Oye mi amor',
      'Juanes - Fotografia',
      'Juanes - Volverte a ver',
      'Juanes - Es por ti',
      'Juanes - Gotas de agua dulce',
      'Alejandro Sanz - Y si fuera ella',
      'Alejandro Sanz - Cuando nadie me ve',
      'Alejandro Sanz - Mi soledad y yo',
      'Alejandro Sanz - No es lo mismo',
      'La Oreja de Van Gogh - Jueves',
      'La Oreja de Van Gogh - 20 de enero',
      'La Oreja de Van Gogh - El 28',
      'Julieta Venegas - Andar conmigo',
      'Julieta Venegas - Algo esta cambiando',
      'Julieta Venegas - Lento',
      'Paulina Rubio - El ultimo adios',
      'Paulina Rubio - Te quise tanto',
      'Paulina Rubio - Causa y efecto',
      'Thalia - No me ensenaste',
      'Thalia - Equivocada',
      'Thalia - Arrasando',
      'Belanova - Por ti',
      'Belanova - Cada que',
      'Belanova - Me pregunto',
      'Miranda - Mentia',
      'Miranda - Prisionero',
      'Miranda - Traicion',
      'Sin Bandera - Mientes tan bien',
      'Sin Bandera - Que lloro',
      'Sin Bandera - Sirena',
      'Reik - Inolvidable',
      'Reik - Creo en ti',
      'Reik - Que vida la mia',
      'Camila - Alejate de mi',
      'Camila - Coleccionista de canciones',
      'Camila - Solo para ti',
      'Alex Ubago - Aunque no te pueda ver',
      'Alex Ubago - A gritos de esperanza',
      'Natalia Lafourcade - Ella es bonita',
      'Natalia Lafourcade - Hasta la raiz',
      'Bacilos - Tabaco y Chanel',
      'Bacilos - Pasos de gigante',
      'Diego Torres - Color esperanza',
      'Carlos Vives - Fruta fresca',
    ],
  },
  {
    id: 'fiesta-familiar-hits',
    name: 'Baraja Bingo - Fiesta Familiar Hits',
    description: 'Hits populares y bailables para cumpleanos, casamientos y reuniones familiares.',
    catalog: {
      categoryId: 'fiesta',
      categoryLabel: 'Fiesta',
      genreLabel: 'Hits populares',
      occasionLabels: ['Cumpleanos', 'Casamientos', 'Familia'],
      energyLabel: 'Bailable',
      decadeLabel: 'Mixto',
      supportedBoardSizes: [3, 4, 5],
      useCaseLabel: 'Eventos familiares con edades mezcladas',
      searchTerms: ['fiesta', 'familia', 'casamiento', 'cumpleanos', 'hits'],
    },
    market: 'AR',
    isPublic: false,
    minimumSongCount: 96,
    seededSongCount: 48,
    spotifyUrl: 'https://open.spotify.com/playlist/6HGpuFLIYAs1NmtjRRvT3J',
    targetSongCount: 120,
    songs: [
      'Gloria Gaynor - I Will Survive',
      'ABBA - Dancing Queen',
      'ABBA - Mamma Mia',
      'Bee Gees - Stayin Alive',
      'Earth Wind and Fire - September',
      'Kool and The Gang - Celebration',
      'Village People - YMCA',
      'Queen - Dont Stop Me Now',
      'Queen - We Will Rock You',
      'Bon Jovi - Livin on a Prayer',
      'Michael Jackson - Billie Jean',
      'Michael Jackson - Beat It',
      'Madonna - Like a Prayer',
      'Madonna - Material Girl',
      'Cyndi Lauper - Girls Just Want to Have Fun',
      'Whitney Houston - I Wanna Dance with Somebody',
      'A-ha - Take On Me',
      'Eurythmics - Sweet Dreams',
      'Toto - Africa',
      'Survivor - Eye of the Tiger',
      'Los Del Rio - Macarena',
      'Las Ketchup - Asereje',
      'Lou Bega - Mambo No 5',
      'Ricky Martin - Maria',
      'Shakira - Waka Waka',
      'Luis Fonsi - Despacito',
      'Don Omar - Danza Kuduro',
      'Daddy Yankee - Gasolina',
      'Celia Cruz - La vida es un carnaval',
      'Juan Luis Guerra - La bilirrubina',
      'Juan Luis Guerra - Ojala que llueva cafe',
      'Marc Anthony - Vivir mi vida',
      'Los Autenticos Decadentes - La guitarra',
      'Los Autenticos Decadentes - Corazon',
      'Los Fabulosos Cadillacs - Matador',
      'Soda Stereo - De musica ligera',
      'Fito Paez - Mariposa tecknicolor',
      'Gilda - No me arrepiento de este amor',
      'Los Palmeras - Bombon asesino',
      'Rafaga - Mentirosa',
      'Rodrigo - Soy cordobes',
      'La Konga - Universo paralelo',
      'Karina - Con la misma moneda',
      'Rombai - Cuando se pone a bailar',
      'Marama - Nena',
      'Turf - Loco un poco',
      'Miranda - Don',
      'Calle 13 - Atrevete te te',
      'ABBA - Waterloo',
      'ABBA - Gimme Gimme Gimme',
      'ABBA - Super Trouper',
      'Bee Gees - Night Fever',
      'Bee Gees - You Should Be Dancing',
      'Earth Wind and Fire - Boogie Wonderland',
      'Earth Wind and Fire - Lets Groove',
      'Kool and The Gang - Get Down On It',
      'Kool and The Gang - Ladies Night',
      'Village People - In The Navy',
      'Queen - Another One Bites The Dust',
      'Queen - Crazy Little Thing Called Love',
      'Bon Jovi - You Give Love A Bad Name',
      'Bon Jovi - Its My Life',
      'Michael Jackson - Thriller',
      'Michael Jackson - Dont Stop Til You Get Enough',
      'Michael Jackson - Bad',
      'Madonna - Like a Virgin',
      'Madonna - Vogue',
      'Madonna - Holiday',
      'Cyndi Lauper - Time After Time',
      'Cyndi Lauper - True Colors',
      'Whitney Houston - How Will I Know',
      'Whitney Houston - I Will Always Love You',
      'A-ha - The Sun Always Shines On TV',
      'Eurythmics - Here Comes The Rain Again',
      'Toto - Hold the Line',
      'Survivor - Burning Heart',
      'Ritchie Valens - La Bamba',
      'The Beatles - Twist And Shout',
      'Lou Bega - I Got A Girl',
      'Ricky Martin - Livin la vida loca',
      'Ricky Martin - La copa de la vida',
      'Shakira - Loca',
      'Shakira - La tortura',
      'Shakira - Hips dont lie',
      'Don Omar - Taboo',
      'Don Omar - Salio el sol',
      'Daddy Yankee - Limbo',
      'Daddy Yankee - Dura',
      'Celia Cruz - Quimbara',
      'Celia Cruz - Rie y llora',
      'Juan Luis Guerra - La travesia',
      'Juan Luis Guerra - Visa para un sueno',
      'Marc Anthony - Valio la pena',
      'Marc Anthony - Tu amor me hace bien',
      'Los Autenticos Decadentes - Loco tu forma de ser',
      'Los Autenticos Decadentes - Los piratas',
      'Los Autenticos Decadentes - Besandote',
      'Los Fabulosos Cadillacs - Vasos vacios',
      'Los Fabulosos Cadillacs - Mal bicho',
      'Soda Stereo - Persiana americana',
      'Fito Paez - El amor despues del amor',
      'Gilda - Fuiste',
      'Gilda - Paisaje',
      'Los Palmeras - El embrujo',
      'Los Palmeras - Olvidala',
      'Rafaga - Una cerveza',
      'Rodrigo - La mano de Dios',
      'Rodrigo - Ocho cuarenta',
      'La Konga - Ya no vuelvas',
      'La Konga - El mismo aire',
      'Karina - Corazon mentiroso',
      'Rombai - Me voy',
      'Rombai - 2 pa 2',
      'Marama - Todo comenzo bailando',
      'Marama - Loquita',
      'Turf - Pasos al costado',
      'Turf - Magia blanca',
      'Miranda - Perfecta',
      'Miranda - Yo te dire',
      'Calle 13 - No hay nadie como tu',
    ],
  },
  {
    id: 'retro-80s-90s-internacional',
    name: 'Baraja Bingo - Retro 80s y 90s Internacional',
    description: 'Clasicos internacionales de los 80s y 90s para eventos adultos.',
    catalog: {
      categoryId: 'retro',
      categoryLabel: 'Retro',
      genreLabel: 'Internacional',
      occasionLabels: ['Adultos', 'Nostalgia'],
      energyLabel: 'Clasicos',
      decadeLabel: '80/90',
      supportedBoardSizes: [3, 4, 5],
      useCaseLabel: 'Eventos adultos, bares y noches retro',
      searchTerms: ['retro', '80s', '90s', 'internacional', 'clasicos'],
    },
    market: 'AR',
    isPublic: false,
    minimumSongCount: 96,
    seededSongCount: 48,
    spotifyUrl: 'https://open.spotify.com/playlist/35rDZobwqYhh2Gv7wmqkma',
    targetSongCount: 120,
    songs: [
      'A-ha - Take On Me',
      'Tears For Fears - Everybody Wants To Rule The World',
      'Eurythmics - Sweet Dreams',
      'Depeche Mode - Enjoy the Silence',
      'New Order - Blue Monday',
      'The Cure - Friday Im In Love',
      'The Police - Every Breath You Take',
      'Bon Jovi - Livin on a Prayer',
      'Guns N Roses - Sweet Child O Mine',
      'Europe - The Final Countdown',
      'Survivor - Eye of the Tiger',
      'Queen - Another One Bites The Dust',
      'Michael Jackson - Billie Jean',
      'Michael Jackson - Thriller',
      'Madonna - Like a Virgin',
      'Madonna - Vogue',
      'Cyndi Lauper - Time After Time',
      'Whitney Houston - I Wanna Dance with Somebody',
      'George Michael - Faith',
      'Prince - Kiss',
      'Toto - Africa',
      'Men At Work - Down Under',
      'Roxette - The Look',
      'Roxette - It Must Have Been Love',
      'Nirvana - Smells Like Teen Spirit',
      'Oasis - Wonderwall',
      'Blur - Song 2',
      'Radiohead - Creep',
      'R.E.M. - Losing My Religion',
      'Red Hot Chili Peppers - Under the Bridge',
      'No Doubt - Dont Speak',
      'Alanis Morissette - Ironic',
      'Spice Girls - Wannabe',
      'Backstreet Boys - I Want It That Way',
      'Britney Spears - Baby One More Time',
      'Aqua - Barbie Girl',
      'Haddaway - What Is Love',
      'Corona - The Rhythm of the Night',
      'La Bouche - Be My Lover',
      'Ace of Base - All That She Wants',
      'Ace of Base - The Sign',
      'Coolio - Gangstas Paradise',
      'MC Hammer - U Cant Touch This',
      'Vanilla Ice - Ice Ice Baby',
      'Cher - Believe',
      'Daft Punk - Around the World',
      'Eiffel 65 - Blue',
      'Smash Mouth - All Star',
      'Tears For Fears - Shout',
      'Tears For Fears - Mad World',
      'Depeche Mode - Personal Jesus',
      'Depeche Mode - Just Cant Get Enough',
      'Depeche Mode - Policy of Truth',
      'New Order - Bizarre Love Triangle',
      'The Cure - Boys Dont Cry',
      'The Cure - Just Like Heaven',
      'The Cure - Lovesong',
      'The Police - Roxanne',
      'The Police - Message in a Bottle',
      'Bon Jovi - You Give Love A Bad Name',
      'Bon Jovi - Always',
      'Bon Jovi - Bed of Roses',
      'Guns N Roses - November Rain',
      'Guns N Roses - Paradise City',
      'Guns N Roses - Welcome To The Jungle',
      'Guns N Roses - Dont Cry',
      'Europe - Carrie',
      'Queen - I Want To Break Free',
      'Queen - Radio Ga Ga',
      'Queen - Under Pressure',
      'Michael Jackson - Beat It',
      'Michael Jackson - Bad',
      'Michael Jackson - Black Or White',
      'Michael Jackson - Smooth Criminal',
      'Madonna - Material Girl',
      'Madonna - Like a Prayer',
      'Madonna - Papa Dont Preach',
      'Cyndi Lauper - Girls Just Want to Have Fun',
      'Cyndi Lauper - True Colors',
      'Whitney Houston - I Will Always Love You',
      'Whitney Houston - How Will I Know',
      'George Michael - Careless Whisper',
      'George Michael - Freedom 90',
      'Prince - Purple Rain',
      'Prince - When Doves Cry',
      'Toto - Hold the Line',
      'Toto - Rosanna',
      'Men At Work - Who Can It Be Now',
      'Roxette - Listen To Your Heart',
      'Roxette - Joyride',
      'Roxette - Sleeping In My Car',
      'Nirvana - Come As You Are',
      'Nirvana - Lithium',
      'Oasis - Dont Look Back In Anger',
      'Oasis - Champagne Supernova',
      'Blur - Girls and Boys',
      'Blur - Parklife',
      'Radiohead - Karma Police',
      'Radiohead - No Surprises',
      'R.E.M. - Shiny Happy People',
      'R.E.M. - Everybody Hurts',
      'R.E.M. - The One I Love',
      'Red Hot Chili Peppers - Californication',
      'Red Hot Chili Peppers - Scar Tissue',
      'Red Hot Chili Peppers - Give It Away',
      'No Doubt - Just A Girl',
      'No Doubt - Spiderwebs',
      'Alanis Morissette - You Oughta Know',
      'Alanis Morissette - Hand In My Pocket',
      'Alanis Morissette - You Learn',
      'Spice Girls - Say Youll Be There',
      'Spice Girls - 2 Become 1',
      'Backstreet Boys - Everybody',
      'Backstreet Boys - As Long As You Love Me',
      'Britney Spears - Oops I Did It Again',
      'Britney Spears - Crazy',
      'Aqua - Doctor Jones',
      'Haddaway - Life',
      'Ace of Base - Beautiful Life',
      'Natalie Imbruglia - Torn',
    ],
  },
  {
    id: 'karaoke-en-espanol',
    name: 'Baraja Bingo - Karaoke en Espanol',
    description: 'Canciones cantables en espanol para bingo musical con coro espontaneo.',
    catalog: {
      categoryId: 'karaoke',
      categoryLabel: 'Karaoke',
      genreLabel: 'Espanol cantable',
      occasionLabels: ['Para cantar', 'Mesa larga'],
      energyLabel: 'Coral',
      decadeLabel: 'Mixto',
      supportedBoardSizes: [3, 4, 5],
      useCaseLabel: 'Reuniones donde todos terminan cantando',
      searchTerms: ['karaoke', 'espanol', 'cantar', 'baladas', 'coro'],
    },
    market: 'AR',
    isPublic: false,
    minimumSongCount: 96,
    targetSongCount: 120,
    songs: [
      'Luis Miguel - Ahora te puedes marchar',
      'Luis Miguel - La incondicional',
      'Luis Miguel - Culpable o no',
      'Cristian Castro - Azul',
      'Cristian Castro - Lloran las rosas',
      'Ricardo Arjona - Mujeres',
      'Ricardo Arjona - Historia de taxi',
      'Alejandro Sanz - Corazon partio',
      'Alejandro Sanz - Amiga mia',
      'Laura Pausini - Se fue',
      'Laura Pausini - Entre tu y mil mares',
      'Franco de Vita - Te amo',
      'Franco de Vita - Un buen perdedor',
      'Sin Bandera - Entra en mi vida',
      'Sin Bandera - Kilometros',
      'Reik - Noviembre sin ti',
      'Reik - Yo quisiera',
      'Camila - Mientes',
      'Camila - Todo cambio',
      'Mana - En el muelle de San Blas',
      'Mana - Clavado en un bar',
      'Shakira - Antologia',
      'Shakira - Inevitable',
      'Juanes - A Dios le pido',
      'Juanes - La camisa negra',
      'La Quinta Estacion - El sol no regresa',
      'La Oreja de Van Gogh - Rosas',
      'La Oreja de Van Gogh - La playa',
      'Julieta Venegas - Me voy',
      'Julieta Venegas - Limon y sal',
      'Miranda - Perfecta',
      'Miranda - Don',
      'Los Enanitos Verdes - Lamento boliviano',
      'Soda Stereo - De musica ligera',
      'Fito Paez - 11 y 6',
      'Andres Calamaro - Flaca',
      'Los Rodriguez - Sin documentos',
      'Vicentico - Los caminos de la vida',
      'Coti - Antes que ver el sol',
      'Diego Torres - Color esperanza',
      'Axel - Celebra la vida',
      'Abel Pintos - Sin principio ni final',
      'Soledad - Tren del cielo',
      'Chaqueno Palavecino - Amor salvaje',
      'Los Nocheros - Roja boca',
      'Gilda - No me arrepiento de este amor',
      'Rodrigo - Lo mejor del amor',
      'Marc Anthony - Vivir mi vida',
      'Luis Miguel - Hasta que me olvides',
      'Luis Miguel - Entregate',
      'Luis Miguel - La bikina',
      'Luis Miguel - Suave',
      'Luis Miguel - Sabor a mi',
      'Cristian Castro - No podras',
      'Cristian Castro - Por amarte asi',
      'Cristian Castro - Volver a amar',
      'Cristian Castro - Lloviendo estrellas',
      'Ricardo Arjona - Fuiste tu',
      'Ricardo Arjona - Dime que no',
      'Ricardo Arjona - Te conozco',
      'Ricardo Arjona - El problema',
      'Alejandro Sanz - Y si fuera ella',
      'Alejandro Sanz - Mi soledad y yo',
      'Alejandro Sanz - No es lo mismo',
      'Alejandro Sanz - Cuando nadie me ve',
      'Laura Pausini - La soledad',
      'Laura Pausini - Amores extranos',
      'Laura Pausini - Vuelve junto a mi',
      'Laura Pausini - Viveme',
      'Franco de Vita - No basta',
      'Franco de Vita - Si la ves',
      'Franco de Vita - Te veo venir soledad',
      'Sin Bandera - Mientes tan bien',
      'Sin Bandera - Que lloro',
      'Sin Bandera - Sirena',
      'Sin Bandera - Suelta mi mano',
      'Reik - Creo en ti',
      'Reik - Que vida la mia',
      'Reik - Inolvidable',
      'Reik - Me niego',
      'Camila - Alejate de mi',
      'Camila - Coleccionista de canciones',
      'Camila - Solo para ti',
      'Camila - Besame',
      'Mana - Rayando el sol',
      'Mana - Oye mi amor',
      'Mana - Bendita tu luz',
      'Mana - Mariposa traicionera',
      'Shakira - Ciega sordomuda',
      'Shakira - Ojos asi',
      'Shakira - Que me quedes tu',
      'Shakira - Pies descalzos',
      'Juanes - Me enamora',
      'Juanes - Volverte a ver',
      'Juanes - Es por ti',
      'Juanes - Fotografia',
      'La Quinta Estacion - Algo mas',
      'La Quinta Estacion - Me muero',
      'La Quinta Estacion - Recuerdame',
      'La Oreja de Van Gogh - Puedes contar conmigo',
      'La Oreja de Van Gogh - Jueves',
      'La Oreja de Van Gogh - 20 de enero',
      'La Oreja de Van Gogh - Cuentame al oido',
      'Julieta Venegas - Andar conmigo',
      'Julieta Venegas - Algo esta cambiando',
      'Julieta Venegas - Lento',
      'Miranda - Mentia',
      'Miranda - Yo te dire',
      'Miranda - Traicion',
      'Los Enanitos Verdes - La muralla verde',
      'Los Enanitos Verdes - Luz de dia',
      'Soda Stereo - Persiana americana',
      'Soda Stereo - Tratame suavemente',
      'Fito Paez - Mariposa tecknicolor',
      'Fito Paez - El amor despues del amor',
      'Andres Calamaro - Paloma',
      'Andres Calamaro - Loco',
      'Vicentico - Solo un momento',
      'Coti - Nada fue un error',
      'Diego Torres - Tratar de estar mejor',
    ],
  },
  {
    id: 'pop-rock-internacional-2000s',
    name: 'Baraja Bingo - Pop Rock Internacional 2000s',
    description: 'Pop rock internacional 2000s para publico adulto joven y nostalgia millennial.',
    catalog: {
      categoryId: 'rock',
      categoryLabel: 'Rock',
      genreLabel: 'Pop rock internacional',
      occasionLabels: ['Millennial', 'Nostalgia'],
      energyLabel: 'Festivalera',
      decadeLabel: '2000s',
      supportedBoardSizes: [3, 4, 5],
      useCaseLabel: 'Amigos, bares y fiestas millennial',
      searchTerms: ['pop rock', 'internacional', '2000s', 'millennial', 'indie'],
    },
    market: 'AR',
    isPublic: false,
    minimumSongCount: 96,
    targetSongCount: 120,
    songs: [
      'The Killers - Mr Brightside',
      'The Killers - Somebody Told Me',
      'Coldplay - Yellow',
      'Coldplay - Viva La Vida',
      'Coldplay - Clocks',
      'Maroon 5 - This Love',
      'Maroon 5 - She Will Be Loved',
      'The Strokes - Last Nite',
      'The Strokes - Reptilia',
      'Franz Ferdinand - Take Me Out',
      'Arctic Monkeys - I Bet You Look Good On The Dancefloor',
      'Arctic Monkeys - Fluorescent Adolescent',
      'Green Day - American Idiot',
      'Green Day - Boulevard of Broken Dreams',
      'Linkin Park - In The End',
      'Linkin Park - Numb',
      'Evanescence - Bring Me To Life',
      'Avril Lavigne - Complicated',
      'Avril Lavigne - Sk8er Boi',
      'Kelly Clarkson - Since U Been Gone',
      'Pink - Get The Party Started',
      'Pink - So What',
      'Beyonce - Crazy In Love',
      'Rihanna - Umbrella',
      'Rihanna - Dont Stop The Music',
      'Lady Gaga - Poker Face',
      'Lady Gaga - Bad Romance',
      'Katy Perry - I Kissed A Girl',
      'Katy Perry - Hot N Cold',
      'Black Eyed Peas - I Gotta Feeling',
      'Black Eyed Peas - Pump It',
      'Outkast - Hey Ya',
      'Gnarls Barkley - Crazy',
      'Amy Winehouse - Rehab',
      'Amy Winehouse - Valerie',
      'Britney Spears - Toxic',
      'Justin Timberlake - Cry Me A River',
      'Justin Timberlake - SexyBack',
      'Nelly Furtado - Maneater',
      'Nelly Furtado - Promiscuous',
      'Shakira - Hips Dont Lie',
      'Sean Paul - Temperature',
      'Usher - Yeah',
      '50 Cent - In Da Club',
      'Daft Punk - One More Time',
      'Gorillaz - Feel Good Inc',
      'The White Stripes - Seven Nation Army',
      'Muse - Supermassive Black Hole',
      'The Killers - When You Were Young',
      'The Killers - Read My Mind',
      'The Killers - Human',
      'Coldplay - The Scientist',
      'Coldplay - Fix You',
      'Coldplay - Speed of Sound',
      'Coldplay - In My Place',
      'Maroon 5 - Makes Me Wonder',
      'Maroon 5 - Sunday Morning',
      'Maroon 5 - Moves Like Jagger',
      'The Strokes - Someday',
      'The Strokes - You Only Live Once',
      'Franz Ferdinand - Do You Want To',
      'Franz Ferdinand - No You Girls',
      'Arctic Monkeys - Do I Wanna Know',
      'Arctic Monkeys - Mardy Bum',
      'Arctic Monkeys - Brianstorm',
      'Green Day - Wake Me Up When September Ends',
      'Green Day - Holiday',
      'Green Day - Basket Case',
      'Linkin Park - What Ive Done',
      'Linkin Park - Crawling',
      'Linkin Park - Faint',
      'Linkin Park - Breaking the Habit',
      'Evanescence - My Immortal',
      'Evanescence - Going Under',
      'Avril Lavigne - Girlfriend',
      'Avril Lavigne - My Happy Ending',
      'Avril Lavigne - Im With You',
      'Kelly Clarkson - Because of You',
      'Kelly Clarkson - Behind These Hazel Eyes',
      'Kelly Clarkson - Breakaway',
      'Pink - Just Like A Pill',
      'Pink - Who Knew',
      'Pink - Raise Your Glass',
      'Beyonce - Single Ladies',
      'Beyonce - Halo',
      'Beyonce - Irreplaceable',
      'Rihanna - Disturbia',
      'Rihanna - Only Girl',
      'Rihanna - We Found Love',
      'Lady Gaga - Just Dance',
      'Lady Gaga - Paparazzi',
      'Lady Gaga - Telephone',
      'Katy Perry - Firework',
      'Katy Perry - California Gurls',
      'Katy Perry - Teenage Dream',
      'Black Eyed Peas - Where Is The Love',
      'Black Eyed Peas - Boom Boom Pow',
      'Black Eyed Peas - Lets Get It Started',
      'Outkast - Ms Jackson',
      'Outkast - Roses',
      'Gnarls Barkley - Smiley Faces',
      'Amy Winehouse - Back To Black',
      'Amy Winehouse - You Know Im No Good',
      'Britney Spears - Womanizer',
      'Britney Spears - Gimme More',
      'Britney Spears - Circus',
      'Justin Timberlake - Rock Your Body',
      'Justin Timberlake - My Love',
      'Justin Timberlake - What Goes Around',
      'Nelly Furtado - Say It Right',
      'Nelly Furtado - Im Like A Bird',
      'Nelly Furtado - All Good Things',
      'Sean Paul - Get Busy',
      'Sean Paul - We Be Burnin',
      'Usher - Burn',
      '50 Cent - Candy Shop',
      'Daft Punk - Harder Better Faster Stronger',
      'Gorillaz - Clint Eastwood',
      'Gorillaz - Dare',
      'Muse - Starlight',
    ],
  },
];
